name: "My Wife Thinks I'm Crazy"
favicon: null
layout_spectrum: 0.99082
typography_spectrum: 0
title: "My Wife Thinks I'm Crazy"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#0060f8'
    - '#00b0d0'
    - '#90b0df'
  brandStrength: 0.5
  lightness: 0.07713621947914362
  saturation: 0.7057394534349442
  rhythmicContrast: 0.9035171286668628
purpose: []
