name: "My Wife Thinks I'm Crazy"
favicon: null
layout_spectrum: 0.03934463718906045
typography_spectrum: 0.9635509608779103
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9007765969727188
  lightness: 0.07713621947914362
  saturation: 0.7057394534349442
  rhythmicContrast: 0.9035171286668628
purpose: []
